name: CI

on:
  # Run tests on PR
  pull_request:
    branches:
      - main
      - develop
      - 'support/*'

  # Optional: Only for post-merge verification (after PR is already approved).
  # Note: PR merge is technically a "push", so this trigger will fire after successful merges.
  # In a proper PR/GitHub workflow, protected branches should only receive PR merges.
  # This trigger only makes sense for:
  # - Hotfixes that bypass PR workflow in emergencies
  # - Unprotected branches that still accept direct pushes (not recommended)
  # - Post-merge verification (redundant if PR tests passed)
  # Remove this entirely if all branches are properly protected with required PR reviews.
  # push:
  #   branches:
  #     - develop

jobs:
  test:
    name: Tests (Wordpress ${{ matrix.wordpress_tag }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mariadb_tag: [
          latest
        ]
        wordpress_tag: [
          5.9.3,
          latest
        ]
        node_tag: [
          22
        ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Setup environment
      uses: ./.github/actions/setup
      with:
        mariadb_tag: ${{ matrix.mariadb_tag }}
        wordpress_tag: ${{ matrix.wordpress_tag }}
        node_tag: ${{ matrix.node_tag }}
        plugin_name: ${{ github.event.repository.name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # 10up/wp_mock 1.1.0 requires phpunit/phpunit ^9.6
    #- name: Setup PHPUnit config
    #  run: |
    #    cd ${{ github.event.repository.name }}/
    #    if [[ $(printf '%s\n' "${{ matrix.wordpress_tag }}" "5.9.3" | sort -V | head -n1) == "${{ matrix.wordpress_tag }}" ]]; then
    #      cp phpunit-9.xml.dist phpunit.xml.dist
    #      echo "Using PHPUnit 9 config for Wordpress ${{ matrix.wordpress_tag }}"
    #    elif [[ $(printf '%s\n' "${{ matrix.wordpress_tag }}" "6.1.1" | sort -V | head -n1) == "${{ matrix.wordpress_tag }}" ]]; then
    #      cp phpunit-10.xml.dist phpunit.xml.dist
    #      echo "Using PHPUnit 10 config for Wordpress ${{ matrix.wordpress_tag }}"
    #    fi

    - name: Run Makefile 'qa' task
      # Variables are passed as Make parameters because the Makefile includes .env
      # which overrides environment variables, so using env: would be ignored.
      # See comment in Makefile before "include .env".
      run: |
        make qa ci \
          PLUGIN_NAME=${{ github.event.repository.name }}

    - name: Run Makefile 'qa test:coverage' task
      if: matrix.wordpress_tag == 'latest'
      run: make qa test:coverage
      
    - name: Upload coverage to Codecov
      if: matrix.wordpress_tag == 'latest'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./${{ github.event.repository.name }}/coverage.xml

    # Security Compliance Note for SonarCloud and Snyk Actions:
    # Both SonarCloud and Snyk require using full commit SHA instead of version tags
    # or @master/@main for security compliance and to prevent supply chain attacks.
    # 
    # To update SHA hashes:
    # - SonarCloud: https://github.com/SonarSource/sonarqube-scan-action/commits/master/
    # - Snyk: https://github.com/snyk/actions/commits/master/
    # Copy the full 40-character commit SHA from the latest commit.
    #
    # SonarCloud Configuration Note:
    # Before running this CI-based analysis, ensure Automatic Analysis is DISABLED
    # in your SonarCloud project settings (Administration > Analysis Method).
    # 
    # Why disable Automatic Analysis:
    # - Automatic Analysis only analyzes main branch + 5 most recent PRs
    # - It cannot analyze feature/develop branches that are part of your git-flow
    # - CI-based analysis provides full control over which branches to analyze
    # - Cannot run both analysis methods simultaneously (causes build failures)
    # - CI-based gives better integration with existing GitHub Actions workflow
    #
    # To disable: SonarCloud UI → Project → Administration → Analysis Method → 
    # Turn OFF "Automatic Analysis" and ensure "CI-based analysis" is enabled.
    - name: SonarQube Scan
      if: matrix.wordpress_tag == 'latest'  
      uses: SonarSource/sonarqube-scan-action@ba6563cca79df854af1350ec3dc5881313ec2d3c
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run Snyk to check for vulnerabilities (PHP)
      if: matrix.wordpress_tag == 'latest'
      continue-on-error: true
      uses: snyk/actions/php@e2221410bff24446ba09102212d8bc75a567237d
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --sarif-file-output=snyk.sarif --file=${{ github.event.repository.name }}/composer.lock
        
    - name: Upload Snyk results to GitHub Code Scanning
      if: matrix.wordpress_tag == 'latest'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
        
    - name: Run Snyk to check for vulnerabilities (Node.js)
      if: matrix.wordpress_tag == 'latest'
      continue-on-error: true
      uses: snyk/actions/node@e2221410bff24446ba09102212d8bc75a567237d
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --file=${{ github.event.repository.name }}/package.json

    - name: Shutdown environment
      uses: ./.github/actions/shutdown
      with:
        cleanup_mode: basic
