name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'support/*'
  pull_request:
    branches:
      - main
      - develop
      - 'support/*'

jobs:
  test:
    name: Tests (Wordpress ${{ matrix.wordpress_tag }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mariadb_tag: [
          latest
        ]
        wordpress_tag: [
          5.9.3,
          latest
        ]
        node_tag: [
          22
        ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Setup environment
      uses: ./.github/actions/setup
      with:
        mariadb_tag: ${{ matrix.mariadb_tag }}
        wordpress_tag: ${{ matrix.wordpress_tag }}
        node_tag: ${{ matrix.node_tag }}
        plugin_name: ${{ github.event.repository.name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # 10up/wp_mock 1.1.0 requires phpunit/phpunit ^9.6
    #- name: Setup PHPUnit config
    #  run: |
    #    cd ${{ github.event.repository.name }}/
    #    if [[ $(printf '%s\n' "${{ matrix.wordpress_tag }}" "5.9.3" | sort -V | head -n1) == "${{ matrix.wordpress_tag }}" ]]; then
    #      cp phpunit-9.xml.dist phpunit.xml.dist
    #      echo "Using PHPUnit 9 config for Wordpress ${{ matrix.wordpress_tag }}"
    #    elif [[ $(printf '%s\n' "${{ matrix.wordpress_tag }}" "6.1.1" | sort -V | head -n1) == "${{ matrix.wordpress_tag }}" ]]; then
    #      cp phpunit-10.xml.dist phpunit.xml.dist
    #      echo "Using PHPUnit 10 config for Wordpress ${{ matrix.wordpress_tag }}"
    #    fi

    - name: Run Makefile 'qa' task
      run: |
        make qa \
          PLUGIN_NAME=${{ github.event.repository.name }}

    - name: Run Makefile 'qa test:coverage' task
      if: matrix.wordpress_tag == 'latest'
      run: make qa test:coverage
      
    - name: Upload coverage to Codecov
      if: matrix.wordpress_tag == 'latest'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./${{ github.event.repository.name }}/coverage.xml

    - name: Shutdown environment
      uses: ./.github/actions/shutdown
      with:
        cleanup_mode: basic
