name: CI

on:
  # Run tests on PR
  pull_request:
    branches:
      - main
      - develop
      - 'support/*'

  # Optional: Only for post-merge verification (after PR is already approved).
  # Note: PR merge is technically a "push", so this trigger will fire after successful merges.
  # In a proper PR/GitHub workflow, protected branches should only receive PR merges.
  # This trigger only makes sense for:
  # - Hotfixes that bypass PR workflow in emergencies
  # - Unprotected branches that still accept direct pushes (not recommended)
  # - Post-merge verification (redundant if PR tests passed)
  # Remove this entirely if all branches are properly protected with required PR reviews.
  # push:
  #   branches:
  #     - develop

jobs:
  test:
    name: Tests (Wordpress ${{ matrix.wordpress_tag }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mariadb_tag: [
          latest
        ]
        wordpress_tag: [
          5.9.3,
          latest
        ]
        node_tag: [
          22
        ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Setup environment
      uses: ./.github/actions/setup
      with:
        mariadb_tag: ${{ matrix.mariadb_tag }}
        wordpress_tag: ${{ matrix.wordpress_tag }}
        node_tag: ${{ matrix.node_tag }}
        plugin_name: ${{ github.event.repository.name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # 10up/wp_mock 1.1.0 requires phpunit/phpunit ^9.6
    #- name: Setup PHPUnit config
    #  run: |
    #    cd ${{ github.event.repository.name }}/
    #    if [[ $(printf '%s\n' "${{ matrix.wordpress_tag }}" "5.9.3" | sort -V | head -n1) == "${{ matrix.wordpress_tag }}" ]]; then
    #      cp phpunit-9.xml.dist phpunit.xml.dist
    #      echo "Using PHPUnit 9 config for Wordpress ${{ matrix.wordpress_tag }}"
    #    elif [[ $(printf '%s\n' "${{ matrix.wordpress_tag }}" "6.1.1" | sort -V | head -n1) == "${{ matrix.wordpress_tag }}" ]]; then
    #      cp phpunit-10.xml.dist phpunit.xml.dist
    #      echo "Using PHPUnit 10 config for Wordpress ${{ matrix.wordpress_tag }}"
    #    fi

    - name: Run Makefile 'qa' task
      # Variables are passed as Make parameters because the Makefile includes .env
      # which overrides environment variables, so using env: would be ignored.
      # See comment in Makefile before "include .env".
      run: |
        make qa ci \
          PLUGIN_NAME=${{ github.event.repository.name }}

    - name: Run Makefile 'qa test:coverage' task
      if: matrix.wordpress_tag == 'latest'
      run: make qa test:coverage
      
    - name: Upload coverage to Codecov
      if: matrix.wordpress_tag == 'latest'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./${{ github.event.repository.name }}/coverage.xml

    - name: SonarQube Scan
      if: matrix.wordpress_tag == 'latest'  
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run Snyk to check for vulnerabilities
      if: matrix.wordpress_tag == 'latest'
      uses: snyk/actions/php@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --file=${{ github.event.repository.name }}/composer.lock
        
    - name: Upload Snyk results to GitHub Code Scanning
      if: matrix.wordpress_tag == 'latest'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
        
    - name: Run Snyk to check Node.js dependencies
      if: matrix.wordpress_tag == 'latest'
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high --file=${{ github.event.repository.name }}/package.json

    - name: Shutdown environment
      uses: ./.github/actions/shutdown
      with:
        cleanup_mode: basic
