name: Release

on:
  push:
    branches:
      - main
      - 'support/*'

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write
  checks: write
  repository-projects: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    outputs:
      version: ${{ steps.version.outputs.version }}
      released: ${{ steps.version.outputs.released }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          # Use a personal access token or GitHub App token with bypass permissions
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        with:
          extra_plugins: |
            @semantic-release/changelog@latest
            @semantic-release/git@latest
            conventional-changelog-conventionalcommits@latest
        env:
          # Use the token with bypass permissions
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        
      - name: Get released version
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$VERSION" ]; then
            echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
            echo "released=true" >> $GITHUB_OUTPUT
            echo "✅ New version to release: ${VERSION#v}"
          else
            echo "released=false" >> $GITHUB_OUTPUT
            echo "❌ No new version to release"
          fi

  deploy:
    name: Deploy Release
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.released == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: v${{ needs.release.outputs.version }}

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          mode: production
          mariadb_tag: latest
          wordpress_tag: 5.9.3 # PHP 8.0.21 for vendor compatibility
          node_tag: 22
          plugin_name: ${{ github.event.repository.name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svn_username: ${{ secrets.SVN_USERNAME }}
          svn_password: ${{ secrets.SVN_PASSWORD }}
          crowdin_project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          crowdin_personal_token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gettext subversion

      #https://github.com/orgs/community/discussions/25641#discussioncomment-3248571
      - name: Run Makefile 'deploy-ci' task
        # Variables are passed as Make parameters because the Makefile includes .env
        # which overrides environment variables, so using env: would be ignored.
        # See comment in Makefile before "include .env".
        run: |
          make deploy-ci \
            MODE=production \
            PLUGIN_NAME=${{ github.event.repository.name }} \
            PLUGIN_VERSION=${{ needs.release.outputs.version }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          # https://github.com/softprops/action-gh-release
          # Note that if you intend to run workflows on the release event (on: { release: { types: [published] } }),
          # you need to use a personal access token for this action, as the default secrets.GITHUB_TOKEN does not trigger another workflow.
          # See: https://github.com/actions/create-release/issues/71
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
          tag_name: v${{ needs.release.outputs.version }}
          files: |
            dist/${{ github.event.repository.name }}.zip
            dist/${{ github.event.repository.name }}--with-git-updater.zip
          generate_release_notes: true

      - name: Shutdown environment
        uses: ./.github/actions/shutdown
        with:
          cleanup_mode: basic
